name: sac_gfcf
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.9 
  - numpy=1.26.2
  - pandas=1.5.3
  - fairlearn=0.7.0
  - gymnasium=0.29.1
  - gym=0.26.2
  - scikit-learn=1.5.1
  - sb3-contrib=2.3.0
  - tensorflow=2.16.2
  - tensorboard=2.16.2
  - shap=0.43.0
  - ipywidgets
  - pip:
    - raiwidgets=0.36.0
    - stable_baselines3=2.3.2